Fix macos tests failing because of tmp dir
test at tests/path-navigator-suggester.test.ts:2:1106
✖ navigator lists folders only, prefix matches first, and nested queries (22.127584ms)
  AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
  + actual - expected

    {
  +   changeDirectory: '/private/var/folders/36/tjdph2t965j8snz9_vkdnw0r0000gn/T/caroushell-nav-TkLat0/src'
  -   changeDirectory: '/var/folders/36/tjdph2t965j8snz9_vkdnw0r0000gn/T/caroushell-nav-TkLat0/src'
    }

      at TestContext.<anonymous> (/Users/runner/work/caroushell/caroushell/tests/path-navigator-suggester.test.ts:36:12)
      at async Test.run (node:internal/test_runner/test:1404:7)
      at async startSubtestAfterBootstrap (node:internal/test_runner/harness:387:3) {
    generatedMessage: true,
    code: 'ERR_ASSERTION',
    actual: { changeDirectory: '/private/var/folders/36/tjdph2t965j8snz9_vkdnw0r0000gn/T/caroushell-nav-TkLat0/src' },
    expected: { changeDirectory: '/var/folders/36/tjdph2t965j8snz9_vkdnw0r0000gn/T/caroushell-nav-TkLat0/src' },
    operator: 'deepStrictEqual',
    diff: 'simple'
  }
Error: Process completed with exit code 1.